[2024-11-09T20:40:34.655+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag3.tsk2 manual__2024-11-09T20:40:33.620874+00:00 [queued]>
[2024-11-09T20:40:34.667+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag3.tsk2 manual__2024-11-09T20:40:33.620874+00:00 [queued]>
[2024-11-09T20:40:34.667+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-09T20:40:34.667+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-09T20:40:34.668+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-09T20:40:34.679+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk2> on 2024-11-09 20:40:33.620874+00:00
[2024-11-09T20:40:34.685+0000] {standard_task_runner.py:55} INFO - Started process 6453 to run task
[2024-11-09T20:40:34.688+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag3', 'tsk2', 'manual__2024-11-09T20:40:33.620874+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag3.py', '--cfg-path', '/tmp/tmpmlij7_u0']
[2024-11-09T20:40:34.689+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask tsk2
[2024-11-09T20:40:34.759+0000] {task_command.py:388} INFO - Running <TaskInstance: trigger_dag3.tsk2 manual__2024-11-09T20:40:33.620874+00:00 [running]> on host a8ff7d7dd89a
[2024-11-09T20:40:34.816+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_dag3
AIRFLOW_CTX_TASK_ID=tsk2
AIRFLOW_CTX_EXECUTION_DATE=2024-11-09T20:40:33.620874+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-09T20:40:33.620874+00:00
[2024-11-09T20:40:34.818+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-11-09T20:40:34.819+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-11-09T20:40:34.834+0000] {subprocess.py:86} INFO - Output:
[2024-11-09T20:40:34.844+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-09T20:40:34.854+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-09T20:40:34.858+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=trigger_dag3, task_id=tsk2, execution_date=20241109T204033, start_date=20241109T204034, end_date=20241109T204034
[2024-11-09T20:40:34.868+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 78 for task tsk2 (Bash command failed. The command returned a non-zero exit code 1.; 6453)
[2024-11-09T20:40:34.914+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-09T20:40:34.936+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
