[2024-11-10T00:12:08.209+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_run2.tsk1 manual__2024-11-10T00:12:07.211365+00:00 [queued]>
[2024-11-10T00:12:08.214+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_run2.tsk1 manual__2024-11-10T00:12:07.211365+00:00 [queued]>
[2024-11-10T00:12:08.214+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-10T00:12:08.214+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-11-10T00:12:08.214+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-10T00:12:08.221+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-11-10 00:12:07.211365+00:00
[2024-11-10T00:12:08.225+0000] {standard_task_runner.py:55} INFO - Started process 17303 to run task
[2024-11-10T00:12:08.228+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_run2', 'tsk1', 'manual__2024-11-10T00:12:07.211365+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dag_run2.py', '--cfg-path', '/tmp/tmpemr3ver7']
[2024-11-10T00:12:08.228+0000] {standard_task_runner.py:83} INFO - Job 131: Subtask tsk1
[2024-11-10T00:12:08.260+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_run2.tsk1 manual__2024-11-10T00:12:07.211365+00:00 [running]> on host a8ff7d7dd89a
[2024-11-10T00:12:08.295+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caubineto@outlook.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_run2
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-11-10T00:12:07.211365+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-10T00:12:07.211365+00:00
[2024-11-10T00:12:08.296+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-11-10T00:12:08.296+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-11-10T00:12:08.301+0000] {subprocess.py:86} INFO - Output:
[2024-11-10T00:12:08.304+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-10T00:12:08.310+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-10T00:12:08.312+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_run2, task_id=tsk1, execution_date=20241110T001207, start_date=20241110T001208, end_date=20241110T001208
[2024-11-10T00:12:08.318+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 131 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 17303)
[2024-11-10T00:12:08.330+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-10T00:12:08.344+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
