[2024-11-10T00:30:29.696+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: default_args_dag.task1 manual__2024-11-10T00:30:17.363223+00:00 [queued]>
[2024-11-10T00:30:29.707+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: default_args_dag.task1 manual__2024-11-10T00:30:17.363223+00:00 [queued]>
[2024-11-10T00:30:29.707+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-10T00:30:29.707+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 4
[2024-11-10T00:30:29.707+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-10T00:30:29.719+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task1> on 2024-11-10 00:30:17.363223+00:00
[2024-11-10T00:30:29.725+0000] {standard_task_runner.py:55} INFO - Started process 18874 to run task
[2024-11-10T00:30:29.731+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'default_args_dag', 'task1', 'manual__2024-11-10T00:30:17.363223+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/default_args.py', '--cfg-path', '/tmp/tmpdprz0crp']
[2024-11-10T00:30:29.732+0000] {standard_task_runner.py:83} INFO - Job 137: Subtask task1
[2024-11-10T00:30:29.853+0000] {task_command.py:388} INFO - Running <TaskInstance: default_args_dag.task1 manual__2024-11-10T00:30:17.363223+00:00 [running]> on host a8ff7d7dd89a
[2024-11-10T00:30:30.033+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caubineto@outlook.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=default_args_dag
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2024-11-10T00:30:17.363223+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-10T00:30:17.363223+00:00
[2024-11-10T00:30:30.037+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-11-10T00:30:30.039+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-11-10T00:30:30.068+0000] {subprocess.py:86} INFO - Output:
[2024-11-10T00:30:30.071+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-10T00:30:30.151+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-10T00:30:30.164+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=default_args_dag, task_id=task1, execution_date=20241110T003017, start_date=20241110T003029, end_date=20241110T003030
[2024-11-10T00:30:30.202+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 137 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 18874)
[2024-11-10T00:30:30.251+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-10T00:30:30.363+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
